### ISSUE TITLE
no downloaded release 2022.04.01 

### ISSUE THREAD

**Issue by brrrr66** [microsoft/SQLCallStackResolver#38]
hi
Downloaded the release 2022.04.01 at launch writes that the release 2022-02-21 is being used, you need to download a new one :(

https://github.com/microsoft/SQLCallStackResolver/releases/download/2022.04.01/SQLCallStackResolver.2022.04.01.zip
MD5 - 4414b59bc26e55cb71c006e8cfcda93d

**Comment by arvindshmicrosoft** [comment]
Thank you for reporting this. [2022.05.27](https://github.com/microsoft/SQLCallStackResolver/releases/tag/2022.05.27) addresses this issue. LMK if you need any further help, or if all is well, it would be appreciated if you can close this issue with a comment acknowledging the fix.

**Comment by brrrr66** [comment]
Thank you, everything is fine!
Respect to you for the program that helped solve the unpleasant problem "c0000005 EXCEPTION_ACCESS_VIOLATION. SQL Server
completes this process."

**Comment by arvindshmicrosoft** [comment]
> Thank you, everything is fine! Respect to you for the program that helped solve the unpleasant problem "c0000005 EXCEPTION_ACCESS_VIOLATION. SQL Server completes this process."

That's great to know! Would you care to share the relevant KB article or fix number which you found relevant after analyzing the stack using SQLCallStackResolver?

**Comment by brrrr66** [comment]
The error appeared unexpectedly, before that everything was ok. Version 15.0.4198.2
Updated to the latest version CU16 15.0.4223.1
The error remained.
I'll ask our database guru to answer in more detail. :)
